# This rule is not used by the project cert-manager-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over certs.k8c.io.despondency.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificate-admin-role
rules:
- apiGroups:
  - certs.k8c.io.despondency.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - certs.k8c.io.despondency.io
  resources:
  - certificates/status
  verbs:
  - get
