# This rule is not used by the project cert-manager-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the certs.k8c.io.despondency.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificate-editor-role
rules:
- apiGroups:
  - certs.k8c.io.despondency.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.k8c.io.despondency.io
  resources:
  - certificates/status
  verbs:
  - get
